version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00" # 13:00(UTC+9)
    ignore:
      - dependency-name: "benc-uk/workflow-dispatch"
        versions: ["121"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00" # 13:00(UTC+9)
    ignore:
      # https://github.com/seleniumhq-community/docker-seleniarm/issues/46
      - dependency-name: "selenium"
        versions: ["4.11.0", "4.12.0", "4.13.0"]
