---
monthly:
  balance:
    labels:
      key: &balance_labels [period]
    metrics:
    - name: mf_monthly_income_jpy
      desc: ホーム > 当月収入
      type: gauge
      labels: *balance_labels
      selector: income
    - name: mf_monthly_expenditure_jpy
      desc: ホーム > 当月支出
      type: gauge
      labels: *balance_labels
      selector: expenditure
    - name: mf_monthly_balance_jpy
      desc: ホーム > 当月収支
      type: gauge
      labels: *balance_labels
      selector: balance
  withdrawal:
    labels:
      key: &withdrawal_labels [name]
      value: [種類・名称]
    metrics:
    - name: mf_monthly_withdrawal_jpy
      desc: トップページ > 引落予定額
      type: gauge
      labels: *withdrawal_labels
    - name: mf_monthly_withdrawal_date
      desc: トップページ > 締め日・引落予定日
      type: info
      values:
      - key: 引落日
        value: 引き落とし日
      labels: *withdrawal_labels

assets:
  total:
    label:
      key: &total_labels []
      value: []
    metrics:
    - name: mf_assets_total_jpy
      desc: 資産 > 資本総額
      type: gauge
      labels: *total_labels
  subtotal:
    labels:
      key: &subtotal_labels [type]
      value: []
    metrics:
    - name: mf_assets_subtotal_jpy
      desc: 資産 > 資産の内訳 > 合計
      type: gauge
      labels: *subtotal_labels
  deposit:
    labels:
      key: &deposit_labels [name,account]
      value: [種類・名称, 保有金融機関]
    metrics:
    - name: mf_assets_deposit_jpy
      desc: 資産 > 預金・現金・暗号資産 > 残高
      type: gauge
      labels: *deposit_labels
      th: 残高
  stock:
    labels:
      key: &stock_labels [code,name,account]
      value: [銘柄コード, 銘柄名, 保有金融機関]
    metrics:
    - name: mf_assets_stock_sum
      desc: 資産 > 株式（現物） > 保有数
      type: gauge
      labels: *stock_labels
      th: 保有数
    - name: mf_assets_stock_average_jpy
      desc: 資産 > 株式（現物） > 平均取得単価
      type: gauge
      labels: *stock_labels
      th: 平均取得単価
    - name: mf_assets_stock_present_jpy
      desc: 資産 > 株式（現物） > 現在値
      type: gauge
      labels: *stock_labels
      th: 現在値
    - name: mf_assets_stock_valuation_jpy
      desc: 資産 > 株式（現物） > 評価額
      type: gauge
      labels: *stock_labels
      th: 評価額
    - name: mf_assets_stock_dayoverday_jpy
      desc: 資産 > 株式（現物） > 前日比
      type: gauge
      labels: *stock_labels
      th: 前日比
    - name: mf_assets_stock_gainloss_jpy
      desc: 資産 > 株式（現物） > 評価損益
      type: gauge
      labels: *stock_labels
      th: 評価損益
    - name: mf_assets_stock_gainloss_percent
      desc: 資産 > 株式（現物） > 評価損益率
      type: gauge
      labels: *stock_labels
      th: 評価損益率
  mutualfund:
    labels:
      key: &mutualfund_labels [name,account]
      value: [銘柄名, 保有金融機関]
    metrics:
    - name: mf_assets_mutualfund_sum
      desc: 資産 > 投資信託 > 保有数
      type: gauge
      labels: *mutualfund_labels
      th: 保有数
    - name: mf_assets_mutualfund_average_jpy
      desc: 資産 > 投資信託 > 平均取得単価
      type: gauge
      labels: *mutualfund_labels
      th: 平均取得単価
    - name: mf_assets_mutualfund_base_jpy
      desc: 資産 > 投資信託 > 平均取得単価
      type: gauge
      labels: *mutualfund_labels
      th: 基準価額
    - name: mf_assets_mutualfund_valuation_jpy
      desc: 資産 > 投資信託 > 評価額
      type: gauge
      labels: *mutualfund_labels
      th: 評価額
    - name: mf_assets_mutualfund_dayoverday_jpy
      desc: 資産 > 投資信託 > 前日比
      type: gauge
      labels: *mutualfund_labels
      th: 前日比
    - name: mf_assets_mutualfund_gainloss_jpy
      desc: 資産 > 投資信託 > 評価損益
      type: gauge
      labels: *mutualfund_labels
      th: 評価損益
    - name: mf_assets_mutualfund_gainloss_percent
      desc: 資産 > 投資信託 > 評価損益率
      type: gauge
      labels: *mutualfund_labels
      th: 評価損益率
  pension:
    labels:
      key: &pension_labels [name]
      value: [名称]
    metrics:
    - name: mf_assets_pension_acquisition_jpy
      desc: 資産 > 年金 > 取得価額
      type: gauge
      labels: *pension_labels
      th: 取得価額
    - name: mf_assets_pension_present_jpy
      desc: 資産 > 年金 > 現在価値
      type: gauge
      labels: *pension_labels
      th: 現在価値
    - name: mf_assets_pension_gainloss_jpy
      desc: 資産 > 年金 > 評価損益
      type: gauge
      labels: *pension_labels
      th: 評価損益
    - name: mf_assets_pension_gainloss_percent
      desc: 資産 > 年金 > 評価損益率
      type: gauge
      labels: *pension_labels
      th: 評価損益率
  point:
    labels:
      key: &point_labels [name,type,account]
      value: [名称, 種類, 保有金融機関]
    metrics:
    - name: mf_assets_point_sum
      desc: 資産 > ポイント・マイル > ポイント・マイル数
      type: gauge
      labels: *point_labels
      th: ポイント・マイル数
    - name: mf_assets_point_rate
      desc: 資産 > ポイント・マイル > 換算レート
      type: gauge
      labels: *point_labels
      th: 換算レート
    - name: mf_assets_point_present_jpy
      desc: 資産 > ポイント・マイル > 現在の価値
      type: gauge
      labels: *point_labels
      th: 現在の価値
    - name: mf_assets_point_expire_date
      desc: 資産 > ポイント・マイル > 有効期限
      type: info
      values:
      - key: expired
        th: 有効期限
      labels: *point_labels

liability:
  total:
    metrics:
    - name: mf_liability_total_jpy
      desc: 負債 > 負債総額
      type: gauge
      labels: []
  subtotal:
    metrics:
    - name: mf_liability_subtotal_jpy
      desc: 負債 > 負債の内訳
      type: gauge
      labels: [type]
  detail:
    labels:
      key: &li_detail_labels [type,name,account]
      value: [種類,名称・説明, 保有金融機関]
    metrics:
    - name: mf_liability_detail_jpy
      desc: 負債 > 負債詳細
      type: gauge
      labels: *li_detail_labels
      th: 残高

budget:
  progress_total:
    metrics:
    - name: mf_budget_progress_total_jpy
      desc: 予算 > 使った金額 > 支出全体
      type: gauge
      labels: &budget_labels [period]
  progress_subtotal:
    metrics:
    - name: mf_budget_progress_subtotal_jpy
      desc: 予算 > 使った金額 > 分類（手元で管理するお金・毎月決まった支出）
      type: gauge
      labels: &budget_category_labels [period, category]
  progress_category:
    metrics:
    - name: mf_budget_progress_category_jpy
      desc: 予算 > 使った金額 > 大項目
      type: gauge
      labels: *budget_category_labels
  balance_total:
    metrics:
    - name: mf_budget_balance_total_jpy
      desc: 予算 > 残り使える金額 > 支出全体
      type: gauge
      labels: *budget_labels
  balance_subtotal:
    metrics:
    - name: mf_budget_balance_subtotal_jpy
      desc: 予算 > 残り使える金額 > 分類（手元で管理するお金・毎月決まった支出）
      type: gauge
      labels: *budget_category_labels
  balance_category:
    metrics:
    - name: mf_budget_balance_category_jpy
      desc: 予算 > 残り使える金額 > 大項目
      type: gauge
      labels: *budget_category_labels
