---
monthly:
  balance:
    url: "https://moneyforward.com/"
    css_selector:
      title: "section#cf-info > div.headline > h2.heading-normal:nth-child(1) > span"
      data: "table#monthly_total_table_home > tbody > tr > td"
  withdrawal:
    url: "https://moneyforward.com/"
    css_selector:
      accounts: "li.account"
      name: "div.heading-accounts"
      updated: "div.heading-accounts > div.date"
      price: "ul.amount > li.minus-color"
      schedule: "ul.amount > li.schedule"
assets:
  url: "https://moneyforward.com/bs/portfolio"
  total_amount:
    css_selector: "section.bs-total-assets > div.heading-radius-box"
  genre:
    css_selector:
      deposit:
        root: "section#portfolio_det_depo > "
        title: "h1"
        amount: "section > h1"
        table: "section > table"
      stock:
        root: "section#portfolio_det_eq > "
        title: "h1"
        amount: "section > h1"
        table: "table"
      mutualfund:
        root: "section#portfolio_det_mf > "
        title: "h1"
        amount: "section > h1"
        table: "table"
      pension:
        root: "section#portfolio_det_pns > "
        title: "h1"
        amount: "section > h1"
        table: "table"
      point:
        root: "section#portfolio_det_po > "
        title: "h1"
        amount: "section > h1"
        table: "table"
liability:
  url: "https://moneyforward.com/bs/liability"
  total_amount:
    css_selector: "section.bs-liability > section > div.heading-radius-box"
  subtotal_amount:
    css_selector: "section.bs-liability > div.liability-summary > section.bs-total-assets > table"
  accounts:
    css_selector:
      table: "div#liability_det > section > section > table"

budget:
  url: "https://moneyforward.com/spending_summaries?offset_month=0"
  css_selector:
    period: "section.progress_table > div.date_range > div.msg_container > div.msg"
    budgets: "section.progress_table > table.table > tbody > tr"
    name: "th"
    progress: "td.amount > div.progress > div > span"
    balance: "td.remaining"
    total_class_name: "total_expense"
    subtotal_class_name: "budget_type_total_expense"
