name: Upload MoneyForward prom data

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@v1.0.5
    - name: Install pipenv
      run: pipx install pipenv
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        cache: pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Install Japanese Fonts
      run: |
        sudo apt install -y fonts-ipafont
        fc-cache -fv
        fc-list | grep -i ipa
    - name: Start XVFB
      run: Xvfb :99 &
    - name: Run scraping
      run: pipenv run main
      env:
        DISPLAY: :99
        MF_EMAIL: ${{ secrets.MF_EMAIL }}
        MF_PASSWORD: ${{ secrets.MF_PASSWORD }}
    - name: setup GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v0
    - name: Upload JSON to GCS
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./container/public/moneyforward.prom
        destination: ${{ secrets.BUCKET_NAME }}/
    - name: Update Prometheus Data in RaspberryPi
      uses: benc-uk/workflow-dispatch@v1
      with:
        repo: legnoh/life-metrics-grafana-deployment
        ref: refs/heads/main
        workflow: Get Latest Metrics Data from GCS
        token: ${{ secrets.PERSONAL_TOKEN }}
